start/start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('table/', include('table.urls', namespace='table')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



from django.conf.urls import url
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

start/studypost/urls.py
from django.urls import path
from . import views

app_name = 'studypost'

urlpatterns = [
    path('notice/<int:id>', views.notice_home, name='notice_home'),
    path('notice_new/<int:id>', views.notice_new, name='notice_new'),

    path('notice_detail/<int:id>/', views.notice_detail, name='notice_detail'),

    path('notice_list/<int:id>/', views.notice_list, name='notice_list'),
    path('notice_edit/<int:id>/', views.notice_edit, name='notice_edit'),
    path('notice_delete/<int:id>/', views.notice_delete, name='notice_delete'),
    path('notice_download/<str:file_path>/', views.file_download, name='notice_download'),

    path('homework_new/<int:id>', views.homework_new, name='homework_new'),

    path('homework_detail/<int:id>/', views.homework_detail, name='homework_detail'),

    path('homework_list/<int:id>/', views.homework_list, name='homework_list'),
    path('homework_edit/<int:id>/', views.homework_edit, name='homework_edit'),
    path('homework_delete/<int:id>/', views.homework_delete, name='homework_delete'),
    path('homework_download/<str:file_path>/', views.file_download, name='homework_download'),
]

start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/studypost/models.py
import re
from django.forms import ValidationError
from django.db import models
from django.urls import reverse
from study.models import Group
from accounts.models import StudyUser
from datetime import datetime



def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')


class Notice(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    title = models.CharField(max_length=20, verbose_name='제목', help_text='글제목')
    content = models.TextField(verbose_name='내용')
    photo = models.ImageField(blank=True, null=True, verbose_name='사진', upload_to='studypost/notice/%Y/%m/%d')
    file = models.FileField(blank=True, null=True, verbose_name='파일 업로드', upload_to='studypost/notice/%Y/%m/%d')
    lnglat = models.CharField(max_length=50, blank=True,
                              validators=[lnglat_validator],
                              verbose_name='장소')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(StudyUser, on_delete=models.CASCADE)


    def get_absolute_url(self):
        return reverse('studypost:notice_detail', args=[self.id])

    def sub_time(self):
        now_time = datetime.now()
        sub_time = now_time - self.created_at
        sub_time = sub_time.seconds//60

        return sub_time


class Homework(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    title = models.CharField(max_length=20, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    photo = models.ImageField(blank=True, null=True, verbose_name='사진', upload_to='studypost/homework/%Y/%m/%d')
    file = models.FileField(blank=True, null=True, verbose_name='파일 업로드', upload_to='studypost/homework/%Y/%m/%d')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(StudyUser, on_delete=models.CASCADE)


    def get_absolute_url(self):
        return reverse('studypost:homework_detail', args=[self.id])

    def sub_time(self):
        now_time = datetime.now()
        sub_time = now_time - self.created_at
        sub_time = sub_time.seconds//60

        return sub_time

start/studypost/forms.py
from django import forms
from widgets.naver_map_point_widget import NaverMapPointWidget
from .models import Notice, Homework



class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = '__all__'
        exclude = ['group', 'author']
        widgets = {
            'lnglat': NaverMapPointWidget,
        }



class HomeworkForm(forms.ModelForm):
    class Meta:
        model = Homework
        fields = '__all__'
        exclude = ['group', 'author']

start/studypost/views.py
import mimetypes
import os
import urllib

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from study.models import Group, Membership
from .models import Notice, Homework
from .forms import NoticeForm, HomeworkForm
from study.views import group_required, manager_required, mn_stf_required


# Create your views here.

@group_required
def notice_home(request, id):
    group = get_object_or_404(Group, id=id)
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    return render(request, 'studypost/notice_home.html', {
        'group': group,
        'usermembership':usermembership,
    })

@group_required
@mn_stf_required
def notice_new(request, id):
    group = get_object_or_404(Group, id=id)
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    if request.method == 'POST':
        form = NoticeForm(request.POST, request.FILES)
        if form.is_valid():
            r = request.POST
            notice = Notice.objects.create(group=group, title=r['title'],
                                           content=r['content'], lnglat=r['lnglat'],
                                           author=request.user,
                                           photo=request.FILES.get('photo', None),
                                           file=request.FILES.get('file', None)
                                           )
            lng, lat = map(float, notice.lnglat.split(','))
            return render(request, 'studypost/notice_detail.html', {
                'group': group,
                'notice': notice,
                'lng': lng,
                'lat': lat,
                'usermembership':usermembership,
            })
    else:
        form = NoticeForm()
    return render(request, 'studypost/notice_new.html', {
        'group': group,
        'form': form,
        'usermembership': usermembership,
    })



def notice_detail(request, id):
    notice = get_object_or_404(Notice, id=id)
    group = notice.group
    lng, lat = map(float, notice.lnglat.split(','))
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    return render(request, 'studypost/notice_detail.html', {
        'notice': notice,
        'lng': lng,
        'lat': lat,
        'group': group,
        'usermembership': usermembership,
    })


def notice_list(request, id):
    group = Group.objects.get(id=id)
    ns = Notice.objects.filter(group=group).order_by('-id')[:3]
    hs = Homework.objects.filter(group=group).order_by('-id')[:3]
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    return render(request, 'studypost/notice_list.html', {
        'notice_list': ns,
        'homework_list': hs,
        'group': group,
        'usermembership': usermembership,
    })


def notice_edit(request, id):
    notice = get_object_or_404(Notice, id=id)
    group = notice.group
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    if request.method == 'POST':
        form = NoticeForm(request.POST, request.FILES, instance=notice)
        if form.is_valid():
            notice = form.save()
            return redirect(notice)
    else:
        form = NoticeForm(instance=notice)
    return render(request, 'studypost/notice_new.html', {
        'form': form,
        'group':group,
        'usermembership': usermembership,
    })


def notice_delete(request, id):
    notice = get_object_or_404(Notice, id=id)
    group = notice.group
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    notice.delete()

    ns = Notice.objects.filter(group=group)

    return render(request, 'studypost/notice_list.html', {
        'group': group,
        'notice_list': ns,
        'usermembership':usermembership,
    })


########################################################



def homework_new(request, id):
    group = Group.objects.get(id=id)
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    if request.method == 'POST':
        form = HomeworkForm(request.POST, request.FILES)
        if form.is_valid():
            r = request.POST
            homework = Homework.objects.create(group=group, title=r['title'],
                                               content=r['content'], author=request.user,
                                               photo=request.FILES.get('photo', None),
                                               file=request.FILES.get('file', None))
            return redirect(homework)
    else:
        form = HomeworkForm()
    return render(request, 'studypost/homework_new.html', {
        'group': group,
        'form': form,
        'usermembership':usermembership,
    })


def homework_detail(request, id):
    homework = get_object_or_404(Homework, id=id)
    group = homework.group

    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    return render(request, 'studypost/homework_detail.html', {
        'group': group,
        'homework': homework,
        'group': group,
        'usermembership': usermembership,
    })



def homework_list(request, id):
    group = Group.objects.get(id=id)
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    hs = Homework.objects.filter(group=group)

    return render(request, 'studypost/homework_list.html', {
        'group': group,
        'homework_list': hs,
        'usermembership': usermembership,
    })


def homework_edit(request, id):

    homework = get_object_or_404(Homework, id=id)

    group = homework.group
    usermembership = get_object_or_404(Membership, group=group, person=request.user)


    if request.method == 'POST':
        form = HomeworkForm(request.POST, request.FILES, instance=homework)
        if form.is_valid():
            homework = form.save()
            return redirect(homework)
    else:
        form = HomeworkForm(instance=homework)
    return render(request, 'studypost/homework_new.html', {
        'group': group,
        'form': form,
        'usermembership':usermembership,
    })



def homework_delete(request, id):
    homework = get_object_or_404(Homework, id=id)
    group = homework.group
    usermembership = get_object_or_404(Membership, group=group, person=request.user)

    homework.delete()

    hs = Homework.objects.filter(group=group)

    return render(request, 'studypost/homework_list.html', {
        'group': group,
        'homework_list': hs,
        'usermembership':usermembership,
    })


def file_download(request, file_path):
    original_filename = file_path.split('\\')[-1]

    fp = open(file_path, 'rb')
    response = HttpResponse(fp.read())
    fp.close()
    type, encoding = mimetypes.guess_type(original_filename)
    if type is None:
        type = 'application/octet-stream'
    response['Content-Type'] = type
    response['Content-Length'] = str(os.stat(file_path).st_size)
    if encoding is not None:
        response['Content-Encoding'] = encoding

    # To inspect details for the below code, see http://greenbytes.de/tech/tc2231/
    if u'WebKit' in request.META['HTTP_USER_AGENT']:
        # Safari 3.0 and Chrome 2.0 accepts UTF-8 encoded string directly.
        filename_header = 'filename=%s' % original_filename.encode('utf-8')
    elif u'MSIE' in request.META['HTTP_USER_AGENT']:
        # IE does not support internationalized filename at all.
        # It can only recognize internationalized URL, so we do the trick via routing rules.
        filename_header = ''
    else:
        # For others like Firefox, we follow RFC2231 (encoding extension in HTTP headers).
        filename_header = 'filename*=UTF-8\'\'%s' % urllib.quote(original_filename.encode('utf-8'))
    response['Content-Disposition'] = 'attachment; ' + filename_header
    return response

start/studypost/templates/studypost/homework_detail.html
{% extends 'group_base.html' %}
{% load imagekit %}

{% block content %}

<script src="https://kit.fontawesome.com/6e27c4910b.js"></script>

<style>

    .info span {
        color: #a6a6a6;
        font-size: 12px;
    }
</style>


<div class="d-flex justify-content-start">
<h3 style="font-family: 'KoPub Dotum'; font-weight: bold;">{{ homework.title }}</h3>

<div class="info d-flex align-items-center">
    {% if homework.sub_time == 0 %}
    <span class="ml-3">| 방금 | {{ homework.author.nickname }}</span>
    {% elif homework.sub_time < 60 %}
    <span class="ml-3">| {{ homework.sub_time }}분 전 | {{ homework.author.nickname }}</span>
    {% else %}
    <span class="ml-3">| {{ homework.created_at|date:"Y-m-d h:i" }} | {{ homework.author.nickname }}</span>
    {% endif %}
</div>
</div>
<br>

<div class="content-wrapper">
    {{ homework.content|linebreaks }}
</div>
<div class="photo-wrapper">
    {% if homework.photo %}
        {% thumbnail "400x300" homework.photo %}
    {% endif %}
</div>

<hr>

<div class="d-flex justify-content-between">
    <div class="wrapper">
        {% if homework.author == request.user %}
        <a href="{% url 'studypost:homework_edit' homework.id %}" style="color: #a6a6a6;
        font-size: 14px;">수정</a>
        <a href="{% url 'studypost:homework_delete' homework.id %}" style="color: #a6a6a6;
        font-size: 14px; margin-left: 10px;">삭제</a>
        {% endif %}
        <a href="{% url 'studypost:notice_list' group.id %}" style="margin-left: 10px;">글목록</a>
    </div>

    <div class="file-wrapper">
        {% if homework.file %}
        <a href="{% url 'studypost:homework_download' homework.file.path %}" style="margin-left: 10px;"><i
                class="fas fa-file-download">첨부파일</i></a>
        {% endif %}
    </div>
</div>

{% endblock %}

start/studypost/templates/studypost/homework_list.html
{% extends 'group_base.html' %}


{% block content %}

<table class="table table-hover table-bordered">
    <thead>
    <tr>
        <th>title</th>
        <th>content</th>
    </tr>
    </thead>
    <tbody>
    {% for homework in homework_list %}
    <tr>
        <td><a href="{% url "studypost:homework_detail" homework.id %}">{{ homework.title }}</a></td>
        <td>{{ homework.content }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

start/studypost/templates/studypost/homework_new.html
{% extends 'group_base.html' %}
{% load imagekit %}

{% block content %}

<script src="https://kit.fontawesome.com/6e27c4910b.js"></script>

<style>
    form {
        font-family: 'KoPub Dotum';
    }

    .btn-default {
        background-color: #1976D2;
        color: #ebebeb;
    }

</style>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text" name="title" style="width: 820px; height: 50px; font-weight: bold; padding: 5px;" placeholder="글 제목" value="{% if form.title.value %}{{ form.title.value }}{% endif %}">

    <textarea type="text" name="content" style="width: 820px; height: 500px; padding: 5px;" placeholder="여기를 눌러서 글을 작성하세요.

스터디 전반에 대해 공지를 할 수 있는 공간입니다.
과제, 이벤트, 홍보 등 여러 소식을 스터디원들에게 알려주세요!
필요하다면 첨부파일을 업로드할 수도 있습니다.">{% if form.content.value %}{{ form.content.value }}{% endif %}</textarea>

    <div class="input-group mt-3" style="width: 820px;">
        <div class="custom-file">
            <input type="file" name="photo" class="custom-file-input" id="inputGroupFile01">
            <label class="custom-file-label" for="inputGroupFile01" aria-describedby="inputGroupFileAddon01">사진 업로드</label>
        </div>
    </div>

    <div class="input-group mt-3 mb-3" style="width: 820px;">
        <div class="custom-file">
            <input type="file" name="file" class="custom-file-input" id="inputGroupFile02">
            <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">첨부 파일</label>
        </div>
    </div>

    <div class="submit-wrapper d-flex justify-content-end">
        <div>
            <input type="submit" class="btn btn-default mt-3" value="글 올리기">
        </div>
    </div>
</form>


{% endblock %}

start/studypost/templates/studypost/notice_detail.html
{% extends 'group_base.html' %}
{% load imagekit %}

{% block content %}

<script type="text/javascript" src="https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=d0vornngin&submodules=geocoder"></script>
<script src="https://kit.fontawesome.com/6e27c4910b.js"></script>

<style>

    .info span {
        color: #a6a6a6;
        font-size: 12px;
    }
</style>


<div class="d-flex justify-content-start">
<h3 style="font-family: 'KoPub Dotum'; font-weight: bold;">{{ notice.title }}</h3>

<div class="info d-flex align-items-center">
    {% if notice.sub_time == 0 %}
    <span class="ml-3">| 방금 | {{ notice.author.nickname }}</span>
    {% elif notice.sub_time < 60 %}
    <span class="ml-3">| {{ notice.sub_time }}분 전 | {{ notice.author.nickname }}</span>
    {% else %}
    <span class="ml-3">| {{ notice.created_at|date:"Y-m-d h:i" }} | {{ notice.author.nickname }}</span>
    {% endif %}
</div>
</div>
<br>

<div class="content-wrapper">
    {{ notice.content|linebreaks }}
</div>
<div class="photo-wrapper">
    {% if notice.photo %}
        {% thumbnail "400x300" notice.photo %}
    {% endif %}
</div>

<div class="border border-primary rounded mt-3" id="map" style="width: 500px; height: 500px;">
</div>

<hr>

<div class="d-flex justify-content-between">
    <div class="wrapper">
        {% if notice.author == request.user %}
        <a href="{% url 'studypost:notice_edit' notice.id %}" style="color: #a6a6a6;
        font-size: 14px;">수정</a>
        <a href="{% url 'studypost:notice_delete' notice.id %}" style="color: #a6a6a6;
        font-size: 14px; margin-left: 10px;">삭제</a>
        {% endif %}
        <a href="{% url 'studypost:notice_list' group.id %}" style="margin-left: 10px;">글목록</a>
    </div>

    <div class="file-wrapper">
        {% if notice.file %}
        <a href="{% url 'studypost:notice_download' notice.file.path %}" style="margin-left: 10px;"><i
                class="fas fa-file-download">첨부파일</i></a>
        {% endif %}
    </div>
</div>
<script>
    var base_position = new naver.maps.LatLng('{{ lat }}','{{ lng }}');
    var dom = document.getElementById('map');
    var map = new naver.maps.Map(dom, {
        center: base_position
    });
    var marker = new naver.maps.Marker({
        position: base_position,
        map: map
    });
    naver.maps.Event.addListener(map, 'click', function(e) {
        marker.setPosition(e.coord)
    });


    var infoWindow = new naver.maps.InfoWindow({
        anchorSkew: true,

        maxWidth: 200,
        backgroundColor: "#eee",
        borderWidth: 1,
        anchorColor: "#eee",
    });

    map.setCursor('pointer');


    function searchCoordinateToAddress(latlng) {

        infoWindow.close();

        naver.maps.Service.reverseGeocode({
            coords: latlng,
            orders: [
                naver.maps.Service.OrderType.ADDR,
                naver.maps.Service.OrderType.ROAD_ADDR
            ].join(',')
        }, function (status, response) {
            if (status === naver.maps.Service.Status.ERROR) {
                return alert('Something Wrong!');
            }

            var items = response.v2.results,
                address = '',
                htmlAddresses = [];

            for (var i = 0, ii = items.length, item, addrType; i < ii; i++) {
                item = items[i];
                address = makeAddress(item) || '';
                addrType = item.name === 'roadaddr' ? '[도로명 주소]' : '[지번 주소]';

                htmlAddresses.push((i + 1) + '. ' + addrType + ' ' + address);
            }

            infoWindow.setContent([
                '<div style="padding:10px;min-width:200px;line-height:150%;">',
                '<h4 style="margin-top:5px; font-family: \'KoPub Dotum\'; font-weight: bold;">모임 장소</h4><br />',
                htmlAddresses.join('<br />'),
                '</div>'
            ].join('\n'));

            infoWindow.open(map, latlng);
        });
    }

    function initGeocoder() {
        map.addListener('click', function (e) {
            searchCoordinateToAddress(e.coord);
        });

        $('#address').on('keydown', function (e) {
            var keyCode = e.which;

            if (keyCode === 13) { // Enter Key
                searchAddressToCoordinate($('#address').val());
            }
        });

        $('#submit').on('click', function (e) {
            e.preventDefault();

            searchAddressToCoordinate($('#address').val());
        });

        var address = new naver.maps.LatLng('{{ lat }}','{{ lng }}');
        searchCoordinateToAddress(address);
    }

    function makeAddress(item) {
        if (!item) {
            return;
        }

        var name = item.name,
            region = item.region,
            land = item.land,
            isRoadAddress = name === 'roadaddr';

        var sido = '', sigugun = '', dongmyun = '', ri = '', rest = '';

        if (hasArea(region.area1)) {
            sido = region.area1.name;
        }

        if (hasArea(region.area2)) {
            sigugun = region.area2.name;
        }

        if (hasArea(region.area3)) {
            dongmyun = region.area3.name;
        }

        if (hasArea(region.area4)) {
            ri = region.area4.name;
        }

        if (land) {
            if (hasData(land.number1)) {
                if (hasData(land.type) && land.type === '2') {
                    rest += '산';
                }

                rest += land.number1;

                if (hasData(land.number2)) {
                    rest += ('-' + land.number2);
                }
            }

            if (isRoadAddress === true) {
                if (checkLastString(dongmyun, '면')) {
                    ri = land.name;
                } else {
                    dongmyun = land.name;
                    ri = '';
                }

                if (hasAddition(land.addition0)) {
                    rest += ' ' + land.addition0.value;
                }
            }
        }

        return [sido, sigugun, dongmyun, ri, rest].join(' ');
    }

    function hasArea(area) {
        return !!(area && area.name && area.name !== '');
    }

    function hasData(data) {
        return !!(data && data !== '');
    }

    function checkLastString(word, lastString) {
        return new RegExp(lastString + '$').test(word);
    }

    function hasAddition(addition) {
        return !!(addition && addition.value);
    }

    naver.maps.onJSContentLoaded = initGeocoder;
</script>


{% endblock %}

start/studypost/templates/studypost/notice_home.html
{% extends 'group_base.html' %}


{% block content %}

<div class="dropdown mt-3">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    공지 올리기
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <a class="dropdown-item" href="{% url "studypost:notice_new" group.id %}">모임 공지</a>
    <a class="dropdown-item" href="{% url "studypost:homework_new" group.id %}">기타 공지</a>
  </div>
</div>

<div>
    <a href="{% url "studypost:notice_list" group.id %}">모임 공지 History</a>
    <a href="{% url "studypost:homework_list" group.id %}">기타 공지 History</a>
</div>

{% endblock %}

start/studypost/templates/studypost/notice_list.html
{% extends 'group_base.html' %}


{% block content %}

<style>

    .table a {
        font-family: 'KoPub Dotum';
        font-size: 14px;
        color: #292929;
    }

    .btn-default {
        background-color: #1976D2;
        color: #ebebeb;
    }

    .table p {
        width: 800px;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        display: block;
        font-size: 14px;
        color: #a6a6a6;
    }

    table span {
        color: #a6a6a6;
        font-size: 12px;
    }

</style>

<div class="d-flex justify-content-between align-items-end">
    <div>
    <h4 style="font-family: 'yg-jalnan', cursive;">모임 공지</h4>
    </div>
    <div class="dropdown mt-3">
        <a class="btn btn-dark dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
            공지 올리기
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'studypost:notice_new' group.id %}" style="color:  #292929;">모임 공지</a>
            <a class="dropdown-item" href="{% url 'studypost:homework_new' group.id %}" style="color:  #292929;">기타
                공지</a>
        </div>
    </div>
</div>

<hr>
<table class="table table-hover table-borderless">
    <tbody>
    {% for notice in notice_list %}
    <tr>
        <td><h5><a href="{% url "studypost:notice_detail" notice.id %}">{{ notice.title }}</a></h5>
            <p>{{ notice.content }}</p>
            {% if notice.sub_time == 0 %}
            <span>방금 | {{ notice.author.nickname }}</span>
            {% elif notice.sub_time < 60 %}
            <span>{{ notice.sub_time }}분 전 | {{ notice.author.nickname }}</span>
            {% else %}
            <span>{{ notice.created_at|date:"Y-m-d h:i" }} | {{ notice.author.nickname }}</span>
            {% endif %}
            <hr></td>
    </tr>
    {% endfor %}
    </tbody>
</table>


<h4 style="font-family: 'yg-jalnan', cursive;">기타 공지</h4>
<hr>
<table class="table table-hover table-borderless">
    <tbody>
    {% for homework in homework_list %}
    <tr>
        <td><h5><a href="{% url "studypost:homework_detail" homework.id %}">{{ homework.title }}</a></h5>
            <p>{{ homework.content }}</p>
            {% if homework.sub_time == 0 %}
            <span>방금 | {{ homework.author.nickname }}</span>
            {% elif homework.sub_time < 60 %}
            <span>{{ homework.sub_time }}분 전 | {{ homework.author.nickname }}</span>
            {% else %}
            <span>{{ homework.created_at|date:"Y-m-d h:i" }} | {{ homework.author.nickname }}</span>
            {% endif %}
            <hr></td>
    </tr>
    {% endfor %}
    </tbody>
</table>




{% endblock %}

start/studypost/templates/studypost/notice_new.html
{% extends 'group_base.html' %}
{% load imagekit %}

{% block content %}

<script src="https://kit.fontawesome.com/6e27c4910b.js"></script>


<style>
    form {
        font-family: 'KoPub Dotum';
    }

    .btn-default {
        background-color: #1976D2;
        color: #ebebeb;
    }

    #id_lnglat {
        display: none;
    }
</style>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="text" name="title" style="width: 820px; height: 50px; font-weight: bold; padding: 5px;" placeholder="글 제목" value="{% if form.title.value %}{{ form.title.value }}{% endif %}">

    <textarea type="text" name="content" style="width: 820px; height: 500px; padding: 5px;" placeholder="여기를 눌러서 글을 작성하세요.

스터디 모임에 대해 공지를 할 수 있는 공간입니다.
모임 시간, 모임 장소, 준비물 등을 스터디원들에게 알려주세요!
필요하다면 첨부파일을 업로드할 수도 있습니다.">{% if form.content.value %}{{ form.content.value }}{% endif %}</textarea>

    <div class="input-group mt-3" style="width: 820px;">
        <div class="custom-file">
            <input type="file" name="photo" class="custom-file-input" id="inputGroupFile01">
            <label class="custom-file-label" for="inputGroupFile01" aria-describedby="inputGroupFileAddon01">사진 업로드</label>
        </div>
        <div class="input-group-append">
            <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
        </div>
    </div>

    <div class="input-group mt-3 mb-3" style="width: 820px;">
        <div class="custom-file">
            <input type="file" name="file" class="custom-file-input" id="inputGroupFile02">
            <label class="custom-file-label" for="inputGroupFile02" aria-describedby="inputGroupFileAddon02">첨부 파일</label>
        </div>
        <div class="input-group-append">
            <span class="input-group-text" id="inputGroupFileAddon02">Upload</span>
        </div>
    </div>

    <div class="submit-wrapper d-flex justify-content-between">
        <div class="fieldWrapper">{{ form.lnglat }}</div>
        <div>
            <input type="submit" class="btn btn-default mt-3" value="글 올리기">
        </div>
    </div>
</form>


{% endblock %}