start/start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('table/', include('table.urls', namespace='table')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



from django.conf.urls import url
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

start/study/urls.py
from django.urls import path
from . import views

app_name = 'study'

urlpatterns = [
    path('all_group_list/', views.all_group_list, name='all_group_list'),
    path('group_list/', views.group_list, name='group_list'),
    path('mystudy/', views.group_mystudy, name='mystudy'),
    path('new/', views.group_new, name='group_new'),
    path('<int:id>/', views.group_detail, name='group_detail'),
    path('<int:id>/update', views.group_update, name='group_update'),
    path('<int:id>/settings_mn', views.group_settings_mn, name='group_settings_mn'),
    path('<int:id>/settings_stf', views.group_settings_stf, name='group_settings_stf'),
    path('<int:id>/mysettings', views.group_mysettings, name='group_mysettings'),
    path('register/<int:id>', views.group_register, name='group_register'),
    path('invitation/<int:invitation_url>/', views.group_registerbyurl, name='group_registerbyurl'),
    path('all_group_detail/<int:id>/', views.all_group_detail, name='all_group_detail'),
    path('member_info/<int:id>/', views.member_info, name='member_info'),
    path('member_info_list/<int:id>', views.member_info_list, name='member_info_list'),

]

start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/study/models.py
import uuid
from datetime import datetime, date, time

from django.db import models

from django.conf import settings
from accounts.models import StudyUser
from django.urls import reverse

# Create your models here


class Group(models.Model):
    group_name = models.CharField(max_length=20, unique=True)
    group_code = models.CharField(max_length=20)
    invitation_url = models.CharField(max_length=20, unique=True, default=uuid.uuid1)

    group_bio = models.CharField(max_length=200, blank=True, null=True, default='그룹 소개를 50자 이내(한줄)로 작성해주세요')
    group_goal = models.CharField(max_length=50, blank=True, null=True, default='그룹 목표를 50자 이내(한줄)로 작성해주세요')
    group_rule = models.TextField(max_length=50, blank=True, null=True, default='그룹 규칙을 작성해주세요')
    late_penalty = models.IntegerField(default="0")
    abscence_penalty = models.IntegerField(default="0")
    notsubmit_penalty = models.IntegerField(default="0")

    group_member = models.ManyToManyField(StudyUser, through='Membership')


    def __str__(self):
        return self.group_name

    def get_absolute_url(self):
        return reverse('study:group_detail', args=[self.id])

    def get_members(self):
        return len(Membership.objects.filter(group=self, status='ACTIVE'))


class Membership(models.Model):
    person = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)

    ROLE_CHOICES = [
        ('MANAGER', 'MANAGER'),
        ('STAFF', 'STAFF'),
        ('MEMBER', 'MEMBER')
    ]
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='MEMBER')

    STATUS_CHOICES = [
        # ('NEEDS_APPROVAL', 'NEEDS_APPROVAL'),
        ('ACTIVE', 'ACTIVE'),
        ('OUT', 'OUT')
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='ACTIVE')
    # 총합 필드
    total_admit = models.IntegerField(default=0, verbose_name='인정 총합')
    total_penalty = models.IntegerField(default=0, verbose_name='벌금 총합')
    # 출석 처리 필드
    penalty_attend = models.IntegerField(default=0, verbose_name='출석 벌금 총합')
    noshow_attend = models.IntegerField(default=0, verbose_name='출석 결석 횟수')
    late_attend = models.IntegerField(default=0, verbose_name='출석 지각 횟수')
    admit_attend = models.IntegerField(default=0, verbose_name='출석 인정')
    # 과제 처리 필드
    penalty_assign = models.IntegerField(default=0, verbose_name='과제 벌금 총합')
    noshow_assign = models.IntegerField(default=0, verbose_name='과제 미제출 횟수')
    admit_assign = models.IntegerField(default=0, verbose_name='과제 인정')
    rank = models.IntegerField(default=0, null=True, verbose_name='등수')


    @property
    def is_manager(self):
        if self.role == 'MANAGER':
            return True
        else:
            return False

    @property
    def is_staff(self):
        if self.role == 'STAFF':
            return True
        else:
            return False

    @property
    def is_mn_stf(self):
        if self.role == 'MANAGER' or self.role == 'STAFF':
            return True
        else:
            return False

    @property
    def is_active(self):
        if self.status == 'ACTIVE':
            return True
        else:
            return False


class UpdateHistory(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    created_at = models.DateTimeField(null=True, verbose_name='업데이트 기준')

start/study/forms.py
from django import forms
from .models import Group

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group

        fields = ['group_name', 'group_code', 'group_bio', 'group_goal']
        labels = {
            'group_name': '',
            'group_code':'',
            'group_bio': '',
            'group_goal': '',
        }

class RegisterForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.fields['group_code'].label = ''

    group_code = forms.CharField()

class GroupProfileForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['group_name', 'group_bio', 'group_goal']

        labels = {
            'group_name': '스터디이름',
            'group_bio': '스터디그룹 소개',
            'group_goal': '스터디 목표'
        }

        # help_texts = {}

start/study/views.py
from datetime import datetime, timezone, date, time
import functools
from random import randint

from django.db.models import F
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from accounts.forms import LoginForm
from accounts.models import StudyUser
from assignment.models import Assignment, Done, Injung_history
from attendance.views import attend_status_function

from attendance.forms import AttendConfirmForm
from attendance.views import sub_timedelta_function

from assignment.forms import DoneForm
from django.urls import reverse
from django.utils.html import format_html

from studypost.models import Notice, Homework
from .forms import GroupForm, RegisterForm, GroupProfileForm
from .models import Group, Membership, UpdateHistory
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

from study.models import Membership


def group_required(func):
    @functools.wraps(func)
    def wrapper(request, id):
        group = get_object_or_404(Group, id=id)
        group_name = group.group_name
        user = request.user
        usergroup_list = [x.group.group_name for x in Membership.objects.filter(person=user, status='ACTIVE')]
        if request.user.is_authenticated and group_name not in usergroup_list:
            return render(request, 'study/group_reject.html', {'group_name': group_name})
            # return HttpResponse("{}그룹 멤버가 아니므로 글을 쓸 수 없습니다.".format(group_name))

        return func(request, id)

    return wrapper


def mn_stf_required(func):
    @functools.wraps(func)
    def wrapper(request, id):
        group = get_object_or_404(Group, id=id)
        group_name = group.group_name
        user = request.user
        membership = Membership.objects.get(group=group, person=user)
        if not membership.is_mn_stf or not membership.is_active:
            # return render(request, 'study/group_reject.html', {'group_name': group_name})
            return HttpResponse("매니저 권한이 필요합니다.")
        return func(request, id)

    return wrapper


def manager_required(func):
    @functools.wraps(func)
    def wrapper(request, id):
        group = get_object_or_404(Group, id=id)
        group_name = group.group_name
        user = request.user
        membership = Membership.objects.get(group=group, person=user)
        if not membership.is_manager or not membership.is_active:
            # return render(request, 'study/group_reject.html', {'group_name': group_name})
            return HttpResponse("매니저 권한이 필요합니다.")
        return func(request, id)

    return wrapper


@login_required
def all_group_list(request):
    gs = Group.objects.all()
    g = request.GET.get('g', '')

    if g:
        gs = gs.filter(group_name__icontains=g)

    return render(request, 'study/all_group_list.html', {
        'all_group_list': gs,
    })


@login_required
def group_list(request):
    user = request.user
    # usergroup_list = [x.group.group_name for x in Membership.objects.filter(person=user, status='ACTIVE')]
    # group_list = Group.objects.filter(group_member=user)
    groups = [x.group.group_name for x in Membership.objects.filter(person=user, status='ACTIVE')]
    gs = Group.objects.filter(group_name__in=groups)
    g = request.GET.get('g', '')
    if g:
        gs = gs.filter(group_name__icontains=g)

    return render(request, 'study/group_list.html', {
        'group_list': gs,
    })


@login_required
def all_group_detail(request, id):
    group = get_object_or_404(Group, id=id)
    # membership_manager = [x.person for x in Membership.objects.filter(group=group, role='MANAGER', status='ACTIVE')]
    # membership_member = [x.person for x in Membership.objects.filter(group=group, role='MEMBER', status='ACTIVE')]

    membership_manager = Membership.objects.filter(group=group, role='MANAGER', status='ACTIVE')
    membership_staff = Membership.objects.filter(group=group, role='STAFF', status='ACTIVE')
    membership_member = Membership.objects.filter(group=group, role='MEMBER', status='ACTIVE')

    return render(request, 'study/all_group_detail.html', {
        'group': group,
        'membership_manager': membership_manager,
        'membership_staff': membership_staff,
        'membership_member': membership_member,
    })


@group_required
def group_detail(request, id):
    group = get_object_or_404(Group, id=id)
    user = request.user
    # membership = [x.person for x in Membership.objects.filter(group=group)]
    membership_manager = Membership.objects.filter(group=group, role='MANAGER', status='ACTIVE')
    membership_staff = Membership.objects.filter(group=group, role='STAFF', status='ACTIVE')
    membership_member = Membership.objects.filter(group=group, role='MEMBER', status='ACTIVE')
    usermembership = Membership.objects.get(group=group, person=user)

    memberships = Membership.objects.filter(group=group, status='ACTIVE').order_by('-total_admit')
    penalty_list = Membership.objects.filter(group=group, status='ACTIVE').order_by('-total_penalty')

    latest_update = UpdateHistory.objects.filter(group=group).order_by('created_at').last()
    attend_posts = group.attend_set.all().order_by('-pk')[:3]
    notice_posts = group.notice_set.all().order_by('-pk')[1:4]
    assign_posts = group.assignment_set.filter(group=group).order_by('-pk')[:3]

    for post in attend_posts:
        post.attend_status = attend_status_function(
            datetime.now(),
            post.init_datetime,
            post.gather_datetime,
            post.expired_datetime
        )
        post.save(update_fields=['attend_status'])

    now = datetime.now()

    latest_notice = Notice.objects.filter(group=group).order_by('created_at').last()
    latest_hw = Homework.objects.filter(group=group).order_by('created_at').last()

    # latest_assignment = "가장 최근 과제 instance"
    latest_assignment = Assignment.objects.filter(group=group).order_by('created_at').last()
    dones = Done.objects.filter(assignment=latest_assignment)
    authors = [x.author for x in dones]
    doneform = DoneForm()
    latest_attend = group.attend_set.all().order_by('pk').last()
    # "가장 최근 출석"
    attendform = AttendConfirmForm()

    try:
        confirm_value = latest_attend.attendconfirm_set.filter(
            attend_user=request.user.nickname,
            attend_check='출석 정보 없음'
        )
        # 출석 여부
        attendform = AttendConfirmForm()
        # "출석코드 입력해서 출석완료하는 form"
        # attend_history = "표로 이 출석에 대한 출석 결과 나옴"

        instances_attend = latest_attend.attendconfirm_set.filter(attend_check='출석').order_by('arrive_time')
        instances_late = latest_attend.attendconfirm_set.filter(attend_check='지각').order_by('arrive_time')
        instances_none = latest_attend.attendconfirm_set.filter(attend_check='출석 정보 없음')
        instances_absence = latest_attend.attendconfirm_set.filter(attend_check='결석')

    except:
        confirm_value = False
        instances_attend = False
        instances_late = False
        instances_none = False
        instances_absence = False

    context = {
        'membership_manager': membership_manager,
        'membership_staff': membership_staff,
        'membership_member': membership_member,
        'usermembership': usermembership,
        'group': group,
        'memberships_zip': zip(memberships, range(1, (len(memberships) + 1))),
        'penalty_list_zip': zip(penalty_list, range(1, (len(penalty_list) + 1))),
        'latest_update': latest_update,
        'attend_posts': attend_posts,
        'notice_posts': notice_posts,
        'assign_posts': assign_posts,

        'now': now,
        'latest_assignment': latest_assignment,
        'dones': dones,
        'doneform': doneform,
        'latest_attend': latest_attend,
        'confirm_value': confirm_value,
        'attendform': attendform,
        'authors': authors,

        'latest_notice':latest_notice,
        'latest_hw': latest_hw,

        'instances_attend':instances_attend,
        'instances_late':instances_late,
        'instances_none':instances_none,
        'instances_absence':instances_absence,
    }

    print(latest_notice)
    print(latest_hw)

    if request.method == 'POST':
        if request.POST.get('assignment', ''):
            doneform = DoneForm(request.POST, request.FILES)
            if doneform.is_valid():
                done = doneform.save(commit=False)
                done.author = request.user
                done.assignment = latest_assignment
                done.index_in_assignment = len(Done.objects.filter(assignment=latest_assignment)) + 1
                done.save()
                return redirect('study:group_detail', id)


        elif request.POST.get('attendance', ''):
            attendform = AttendConfirmForm(request.POST)
            if attendform.is_valid():
                input_attend_number = attendform.cleaned_data['input_number']
                attend_number = latest_attend.attendance_number

                if attend_number == input_attend_number:

                    # 결석 인스턴스 가져오기
                    attending_member = latest_attend.attendconfirm_set.get(attend_user=request.user.nickname)

                    # 시간처리
                    state_time = latest_attend.gather_datetime
                    arrive_time = datetime.now()
                    sub_time_arrange = state_time - arrive_time
                    sub_time = sub_timedelta_function(sub_time_arrange)

                    # 지각, 출석 기록
                    if latest_attend.attend_status == '정상 출석 가능':
                        attending_member.arrive_time = arrive_time
                        attending_member.sub_time = sub_time
                        attending_member.attend_check = '출석'
                        attending_member.save()
                        usermembership.admit_attend += 1  # ㅇㅈ하나 추가
                        usermembership.total_admit += 1
                        usermembership.save()

start/study/templates/study/all_group_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-4" style="border:4px solid #1976D2; border-radius: 20px">
                <div style="font-size: 20px; font-family: yg-jalnan; color: #1976D2; margin:20px 0px">
                    스터디 상세정보
                </div>
                <div style="font-size: 20px; text-align: left; background-color: #F2F2F2; padding: 10px">
                    <strong>그룹 이름</strong> : {{ group.group_name }}<br/>
                    <strong>그룹 소개</strong> : {{ group.group_bio }}<br/>
                    <strong>그룹 목표</strong> : {{ group.group_goal }}
                </div>
                <div>
                    {% for member in membership_manager %}
                        <div style="color:dodgerblue;font-size: 20px;margin:10px 0px">
                            <strong>스터디장:</strong> {{ member.person.nickname }}({{ member.person.username }})
                        </div>
                    {% endfor %}
                </div><hr/>
                <div style="margin-bottom:20px">
                    <a href="{% url "study:group_register" group.id %}">스터디 가입하기</a>
                </div>
            </div>
            <div class="col-lg-4"></div>
        </div>
    </div>


{% endblock %}

start/study/templates/study/all_group_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-10">
                <div style="text-align: left">
                    <div style="text-align: left;font-size: 30px;color: #1976D2">
                        <strong>전체 스터디그룹 보기</strong>
                    </div>
                    <div class="search_bar" style="text-align: right">
                        <form action="" method="get">
                            <input type="text" name="g" value="{{ g }}"/>
                            <input type="submit" value="검색" class="btn btn-primary"
                                   style="width: 52px; height: 35px">
                        </form>
                    </div>
                    <br/>
                    <div style="text-align: left">
                        <small>그룹명을 클릭하면 스터디에 가입할 수 있습니다</small>
                    </div>
                </div>
                <div>
                    <table class="table table-hover table-bordered">
                        <thead>
                        <tr>
                            <th>그룹명</th>
                            <th>그룹 소개</th>
                            <th>그룹 목표</th>
                        </tr>
                        </thead>

                        <tbody>

                        {% for group in all_group_list %}
                            <tr>
                                <td><a href="{% url "study:group_register" group.id %}">{{ group.group_name }}</a></td>
                                <td>{{ group.group_bio }}</td>
                                <td>{{ group.group_goal }}</td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
                <div>
                    <a href="{% url 'study:group_new' %}" class="btn btn-primary">스터디 만들기</a>
                </div>
            </div>
            <div class="col-lg-1"></div>
        </div>
    </div>

{% endblock %}

start/study/templates/study/group_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

start/study/templates/study/group_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-10">
                <div style="text-align: left;font-size: 30px;color: #1976D2">
                        <strong>나의 스터디그룹 보기</strong>
                    </div>
                <div class="search_bar" style="text-align: right">
                    <form action="" method="get">
                        <input type="text" name="g" value="{{ g }}"/>
                        <input type="submit" value="검색" class="btn btn-primary">
                    </form><br/>
                </div>
            </div>
            <div class="col-lg-1"></div>

        </div>
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-10 mb-5">
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th>그룹명</th>
                        <th>그룹 목표</th>
                        <th>그룹 소개</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for group in group_list %}
                        <tr>
                            <td><a href="{% url "study:group_detail" group.id %}">{{ group.group_name }}</a></td>
                            <td>{{ group.group_goal }}</td>
                            <td>{{ group.group_bio }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-1"></div>
        </div>
    </div>




{% endblock %}

start/study/templates/study/group_mysettings.html
{% extends 'group_base.html' %}

{% block content %}

<div class="row">
<div class="col-12">
    <ul class="nav nav-pills nav-fill" id="pills-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-attendtable" role="tab" aria-controls="pills-attendtable" aria-selected="true">내 정보 수정</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-assignment" role="tab" aria-controls="pills-assignment" aria-selected="false">그룹 탈퇴</a>
        </li>
    </ul>
</div>
</div>
    <div class="row">

    <div class="tab-content col-8" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-attendtable" role="tabpanel" aria-labelledby="pills-attendtable-tab">
            <h5>나의 다짐</h5>

            <p>무덤에서 가장 부자가 되는 일 따윈 내게 전혀 중요하지 않다.</p>
<p>매일 밤 잠자리에 들 때마다</p>
            <p>정말 놀랄만한 일을 했다고 말하는 것.</p>
            <p>그것이 나에게 가장 중요하다.</p>
<p>- 스티브 잡스</p>
        </div>
        <div class="tab-pane fade" id="pills-assignment" role="tabpanel" aria-labelledby="pills-assignment-tab">
            <p>그룹을 탈퇴하면 재가입이 불가능하며,</p>
            <p>그룹페이지에 들어가 그룹과 관련된 내 정보를 열람할 수 없습니다.</p>

            <form action="" method="POST">
                {% csrf_token %}
                {% if membership.is_manager %}
                <input type="hidden" name="out" value="">
                <button onclick="return alert('방장 권한을 먼저 위임하세요.');">그룹 탈퇴</button>
                </input>
                {% else %}
                <input type="hidden" name="out" value="out">
                <button class="btn btn-primary" onclick="return confirm('그룹을 탈퇴하면 재가입이 불가능하며, ' +
     '그룹페이지에 들어가 그룹과 관련된 내 정보를 열람할 수 없습니다. ' +
      '정말 탈퇴하겠습니까?');">그룹 탈퇴
                </button>
                </input>
                {% endif %}

            </form>

        </div>
    </div>

</div>

{% endblock %}

start/study/templates/study/group_mystudy.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-10">

                <div class="accordion" id="accordionExample">

                    <div class="card">
                        <div class="card-header" id="headingOne">
                            <h2 class="mb-0">
                                <button style="font-size: 25px" class="btn btn-link" type="button" data-toggle="collapse"
                                        data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    나의 스터디 보기
                                </button>
                            </h2>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                             data-parent="#accordionExample">
                            <div class="card-body">
                                <div>
                                    <img src="{% static 'img/mystudy.png' %}" style="width:175px;height: 210px"/>
                                </div><br/>
                                <table class="table table-hover table-bordered">
                                    <thead>
                                    <tr>
                                        <th>스터디명</th>
                                        <th>스터디 목표</th>
                                        <th>스터디 소개</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for group in group_list %}
                                        <tr>
                                            <td>
                                                <a href="{% url "study:group_detail" group.id %}">{{ group.group_name }}</a>
                                            </td>
                                            <td>{{ group.group_goal }}</td>
                                            <td>{{ group.group_bio }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>


                        <div class="card">
                            <div class="card-header" id="headingTwo">
                                <h2 class="mb-0">
                                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                            data-target="#collapseTwo" aria-expanded="false"
                                            aria-controls="collapseTwo">
                                        <a href="{% url 'study:all_group_list' %}" style="font-size: 25px">스터디 찾기</a>
                                    </button>
                                </h2>
                            </div>
                        </div>



                        <div class="card">
                            <div class="card-header" id="headingThree">
                                <h2 class="mb-0">
                                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                            data-target="#collapseThree" aria-expanded="false"
                                            aria-controls="collapseThree">
                                        <a href="{% url 'study:group_new' %}" style="font-size: 25px">스터디 만들기</a>
                                    </button>
                                </h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-1"></div>
                </div>
            </div>

{% endblock %}

start/study/templates/study/group_new.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-10" style="text-align: left;font-size: 30px;padding:20px 0px;margin:0px 18px;color: #1976D2">
                <strong>스터디 만들기</strong>
            </div>
            <div class="col-lg-1"></div>
        </div>
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-5">
                <div style="text-align: left; background-color: #ffdbad; padding:3px;">
                    <div style="font-size: 30px"><strong>*스터디 만들기 유의사항*</strong></div>
                    <div>
                        <img src="{% static 'img/caution.png' %}" style="width:200px;height: 210px;"/>
                    </div>
                    <br/>
                    <p style="font-size: 15px; margin-left: 10px"><strong>- 스터디를 만들면 자동으로 스터디장이 됩니다<br/>
                    - 스터디장 권한은 그룹 관리 탭의 그룹 설정에서 위임할 수 있습니다<br/>
                        - 스터디원이 그룹에 가입하기 위해서는 그룹 코드를 알아야 합니다</strong></p>
                </div>
            </div>
            <div class="col-lg-5" style="text-align: left">
                <form action="" method="post">
                    {% csrf_token %}
                    <div>
                        <div style="text-align: left; font-size: 20px">그룹이름</div>
                        {{ form.group_name|as_crispy_field }}
                    </div>
                    <div>
                        <div style="text-align: left; font-size: 20px">그룹코드</div>
                        {{ form.group_code|as_crispy_field }}
                    </div>
                    <div>
                        <div style="text-align: left; font-size: 20px">한줄그룹소개</div>
                        {{ form.group_bio|as_crispy_field }}
                    </div>
                    <div>
                        <div style="text-align: left; font-size: 20px">한줄그룹목표</div>
                        {{ form.group_goal|as_crispy_field }}
                    </div>
                    <input type="submit" class="btn btn-primary" value="그룹 만들기">
                </form>
            </div>
            <div class="col-lg-1"></div>
        </div>
    </div>

{% endblock %}

start/study/templates/study/group_registerbyurl_fail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <div style="margin-top: 120px">
        <div>
            <img src="{% static 'img/no.png' %}" style="width:175px;height: 230px"/>
        </div><br/>
        <div>
            <h3>이미 탈퇴/가입된 그룹입니다.</h3>
        </div>
        <div>
            <a href="{% url "home" %}">
            <button>홈화면으로 돌아가기</button>
        </a>
        </div>
    </div>
{% endblock %}