start/attendance/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

app_name = 'attendance'

urlpatterns = [
    path('<int:group_id>/', views.attend_list, name='attend_list'),
    path('<int:group_id>/detail/<int:detail_id>', views.attend_detail, name='attend_detail'),
    path('<int:group_id>/new/', views.attend_new, name='attend_new'),
    path('<int:detail_id>/edit', views.attend_edit, name='attend_edit'),
    path('<int:detail_id>/delete', views.attend_delete, name='attend_delete'),
]

start/start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('table/', include('table.urls', namespace='table')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



from django.conf.urls import url
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

start/study/urls.py
from django.urls import path
from . import views

app_name = 'study'

urlpatterns = [
    path('all_group_list/', views.all_group_list, name='all_group_list'),
    path('group_list/', views.group_list, name='group_list'),
    path('mystudy/', views.group_mystudy, name='mystudy'),
    path('new/', views.group_new, name='group_new'),
    path('<int:id>/', views.group_detail, name='group_detail'),
    path('<int:id>/update', views.group_update, name='group_update'),
    path('<int:id>/settings_mn', views.group_settings_mn, name='group_settings_mn'),
    path('<int:id>/settings_stf', views.group_settings_stf, name='group_settings_stf'),
    path('<int:id>/mysettings', views.group_mysettings, name='group_mysettings'),
    path('register/<int:id>', views.group_register, name='group_register'),
    path('invitation/<int:invitation_url>/', views.group_registerbyurl, name='group_registerbyurl'),
    path('all_group_detail/<int:id>/', views.all_group_detail, name='all_group_detail'),
    path('member_info/<int:id>/', views.member_info, name='member_info'),
    path('member_info_list/<int:id>', views.member_info_list, name='member_info_list'),

]

start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/attendance/models.py
from datetime import datetime

from django.db import models
from study.models import Group
from accounts.models import StudyUser


class Attend(models.Model):     # 모델폼으로 구현
    ATTEND_STATUS =[
        ('출석 시작 전', '출석 시작 전'),
        ('정상 출석 가능', '정상 출석 가능'),
        ('지각 출석 가능', '지각 출석 가능'),
        ('출석 시간 만료', '출석 시간 만료')
    ]
    attendance = models.ForeignKey(Group, on_delete=models.CASCADE)
    attendance_number = models.CharField(max_length=5, verbose_name='출석확인번호')
    title = models.CharField(max_length=30, verbose_name='출석 제목')
    init_datetime = models.DateTimeField(verbose_name='출석가능 시작시간')
    gather_datetime = models.DateTimeField(verbose_name='모임 날짜와 시간')
    expired_datetime = models.DateTimeField(verbose_name='출석가능 만료시간')
    attend_status = models.CharField(max_length=15, choices=ATTEND_STATUS, default='출석불가')
    attend_data_checked = models.BooleanField(default=False, verbose_name='결석 처리 여부')

    def get_set(self):
        return self.attendconfirm_set.all()

    def attended(self):
        return [x.person for x in AttendConfirm.objects.filter(attend=self, attend_check='출석')]

    def late(self):
        return [x.person for x in AttendConfirm.objects.filter(attend=self, attend_check='지각')]

    def absent(self):
        return [x.person for x in AttendConfirm.objects.filter(attend=self, attend_check='결석')]

    def sub_time(self):
        now_time = datetime.now()
        sub_time = self.expired_datetime - self.gather_datetime
        sub_time = sub_time.seconds//60
        return sub_time


class AttendConfirm(models.Model):  # 템플릿 인풋으로 폼 구현
    ATTEND_CHANCE = [
        ('출석 정보 없음', '출석 정보 없음'),
        ('지각', '지각'),
        ('출석', '출석'),
        ('결석', '결석')
    ]
    attend = models.ForeignKey(Attend, on_delete=models.CASCADE)
    person = models.ForeignKey(StudyUser, on_delete=models.CASCADE)
    attend_user = models.CharField(max_length=20, verbose_name='출석 닉네임')
    arrive_time = models.DateTimeField(null=True, blank=True, verbose_name='도착 시간')
    sub_time = models.IntegerField(null=True, blank=True, verbose_name='시간 차이')
    attend_check = models.CharField(max_length=20, choices=ATTEND_CHANCE, default='없음')

start/attendance/forms.py
from django import forms
# from django.contrib.auth.forms import AuthenticationForm
from django.forms import DateInput

# from start.accounts.models import StudyUser
from .models import Attend


class AttendForm(forms.ModelForm):    # attend를 만들어준다
    AMPM_CHOICES = (
        ('', '오전오후'),
        ('AM', '오전'),
        ('PM', '오후')
    )

    TIME_CHOICES = (
        ('', '시각을 고르세요'),
        (1, '1'), (2, '2'), (3, '3'), (4, '4'),
        (5, '5'), (6, '6'), (7, '7'), (8, '8'),
        (9, '9'), (10, '10'), (11, '11'), (0, '12'),
    )

    MINUTE_CHOICES = (
        ('', '분을 고르세요'),
        (0, '00'), (5, '05'), (10, '10'), (15, '15'),
        (20, '20'), (25, '25'), (30, '30'), (35, '35'),
        (40, '40'), (45, '45'), (50, '50'), (55, '55'),
    )

    gather_date = forms.DateField(
        widget=DateInput(attrs={'type': 'date'}),
        label='모임 날짜'
    )
    gather_time_ampm = forms.ChoiceField(label='이번 모임은', choices=AMPM_CHOICES)
    gather_time_hour = forms.ChoiceField(label='시', choices=TIME_CHOICES)
    gather_time_minute = forms.ChoiceField(label='분', choices=MINUTE_CHOICES)
    expired_timedelta = forms.IntegerField(label='분 동안 출석 가능합니다')

    class Meta:
        model = Attend
        fields = ['title', 'attendance_number']
        labels = {
            'title': '제목',
            'attendance_number': '출석 코드',
        }


class AttendConfirmForm(forms.Form):
    input_number = forms.CharField(label='출석번호 입력')

start/attendance/views.py
import functools

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from attendance.forms import AttendForm, AttendConfirmForm
from study.models import Group, Membership
from datetime import timedelta, datetime, time
from attendance.models import Attend
from study.models import Membership


def group_required(func):
   @functools.wraps(func)
   def wrapper(request, **kwargs):
       group = get_object_or_404(Group, id=kwargs['group_id'])
       group_name = group.group_name
       user = request.user
       usergroup_list = [x.group.group_name for x in Membership.objects.filter(person=user, status='ACTIVE')]
       if request.user.is_authenticated and group_name not in usergroup_list:
           return render(request, 'study/group_reject.html', {'group_name':group_name})
           # return HttpResponse("{}그룹 멤버가 아니므로 글을 쓸 수 없습니다.".format(group_name))

       return func(request, **kwargs)
   return wrapper


def mn_stf_required(func):
    @functools.wraps(func)
    def wrapper(request, **kwargs):
        group = get_object_or_404(Group, id=kwargs['group_id'])
        group_name = group.group_name
        user = request.user
        membership = Membership.objects.get(group=group, person=user)
        if not membership.is_mn_stf or not membership.is_active:
            # return render(request, 'study/group_reject.html', {'group_name': group_name})
            return HttpResponse("매니저 권한이 필요합니다.")
        return func(request, **kwargs)
    return wrapper


def sub_timedelta_function(time_delta):
    if time_delta.days == -1:
        return (86400 - time_delta.seconds) // 60
    elif time_delta.days == 0:
        return -(time_delta.seconds // 60 + 1)


def gather_time_hour_function(time_hour, time_ampm):
    if time_ampm == 'PM':
        gather_time_hour_processed = int(time_hour) + 12
    else:
        gather_time_hour_processed = int(time_hour)
    return gather_time_hour_processed


def attend_status_function(now_time, init_time, state_time, expired_time):
    if now_time < init_time:
        status = '출석 시작 전'
    elif init_time <= now_time <= state_time:
        status = '정상 출석 가능'
    elif state_time <= now_time <= expired_time:
        status = '지각 출석 가능'
    elif expired_time < now_time:
        status = '출석 시간 만료'
    return status

@group_required
def attend_list(request, group_id):  # 리스트와 디테일 템플릿 거의 동일하게
    group = get_object_or_404(Group, id=group_id)
    usermembership = Membership.objects.get(group=group, person=request.user)

    posts = group.attend_set.all().order_by('-pk')[:5]
    for post in posts:
        post.attend_status = attend_status_function(
            datetime.now(),
            post.init_datetime,
            post.gather_datetime,
            post.expired_datetime
        )
        post.save()
    context = {'posts': posts, 'group': group, 'usermembership':usermembership,}
    return render(request, 'attendance/attend_list.html', context)

@group_required
def attend_detail(request, group_id, detail_id):
    group = get_object_or_404(Group, id=group_id)
    usermembership = Membership.objects.get(group=group, person=request.user)

    attend = group.attend_set.get(id=detail_id)
    membership = group.membership_set.get(person=request.user)
    posts = group.attend_set.all().order_by('-pk')[:5]

    if request.method == 'POST':
        form = AttendConfirmForm(request.POST)

        # 중복 출석 방지
        confirm_value = attend.attendconfirm_set.filter(
            attend_user=request.user.nickname,
            attend_check='출석 정보 없음'
        )

        if confirm_value:
            if form.is_valid():
                input_attend_number = request.POST['input_number']
                attend_number = attend.attendance_number

                if attend_number == input_attend_number:

                    # 결석 인스턴스 가져오기
                    attending_member = attend.attendconfirm_set.get(attend_user=request.user.nickname)

                    # 시간처리
                    state_time = attend.gather_datetime
                    arrive_time = datetime.now()
                    sub_time_arrange = state_time - arrive_time
                    sub_time = sub_timedelta_function(sub_time_arrange)

                    # 지각, 출석 기록
                    if attend.attend_status == '정상 출석 가능':
                        attending_member.arrive_time = arrive_time
                        attending_member.sub_time = sub_time
                        attending_member.attend_check = '출석'
                        attending_member.save()
                        membership.admit_attend += 1    # ㅇㅈ하나 추가
                        membership.total_admit += 1
                        membership.save()
                        messages.success(request, '성공적으로 출석했습니다!')
                        return redirect(resolve_url('attendance:attend_detail', group.id, attend.id))

                    elif attend.attend_status == '지각 출석 가능':
                        attending_member.arrive_time = arrive_time
                        attending_member.sub_time = sub_time
                        attending_member.attend_check = '지각'
                        attending_member.save()
                        membership.late_attend += 1    # 지각 횟수 한번 추가
                        membership.save()
                        messages.success(request, '지각입니다ㅜㅜ')
                        return redirect(resolve_url('attendance:attend_detail', group.id, attend.id))

                else:
                    messages.error(request, '출석 코드가 일치하지 않습니다')
                    return redirect(resolve_url('attendance:attend_detail', group.id, attend.id))
            else:
                messages.error(request, '출석 코드에는 숫자만 입력해주세요')
                return redirect(resolve_url('attendance:attend_detail', group.id, attend.id))
        else:
            messages.error(request, '이미 출석하셨습니다')
            return redirect(resolve_url('attendance:attend_detail', group.id, attend.id))
    else:
        instances_attend = attend.attendconfirm_set.filter(attend_check='출석').order_by('arrive_time')
        instances_late = attend.attendconfirm_set.filter(attend_check='지각').order_by('arrive_time')
        instances_none = attend.attendconfirm_set.filter(attend_check='출석 정보 없음')
        instances_absence = attend.attendconfirm_set.filter(attend_check='결석')
        form = AttendConfirmForm()
        context = {
            'posts': posts,
            'group': group,
            'usermembership':usermembership,
            'attend': attend,
            'form': form,
            'instances_attend': instances_attend,
            'instances_late': instances_late,
            'instances_none': instances_none,
            'instances_absence': instances_absence,
        }
        return render(request, 'attendance/attend_detail.html', context)


@group_required
@mn_stf_required
def attend_new(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    usermembership = get_object_or_404(Membership, group=group, person=request.user)
    group.membership_set.get(person=request.user)
    group_members = group.membership_set.all()

    if request.method == 'POST':
        form = AttendForm(request.POST)

        if form.is_valid():
            gather_date = form.cleaned_data['gather_date']

            gather_time = time(
                gather_time_hour_function(
                    form.cleaned_data['gather_time_hour'],
                    form.cleaned_data['gather_time_ampm']
                ),
                int(form.cleaned_data['gather_time_minute'])
            )

            gather_datetime = datetime.combine(gather_date, gather_time)
            init_datetime = gather_datetime - timedelta(minutes=60)
            expired_datetime = gather_datetime + timedelta(
                minutes=form.cleaned_data['expired_timedelta']
            )

            new_attend = group.attend_set.create(
                title=form.cleaned_data['title'],
                attendance_number=form.cleaned_data['attendance_number'],
                gather_datetime=gather_datetime,
                init_datetime=init_datetime,
                expired_datetime=expired_datetime,
            )

            for member in group_members:
                new_attend.attendconfirm_set.create(
                    person=member.person,
                    attend_user=member.person.nickname,
                    attend_check='출석 정보 없음'
                )

        return redirect(resolve_url('attendance:attend_list', group_id=group.id))

    else:
        form = AttendForm()
        return render(request, 'attendance/attend_new.html', {
            'group':group,
            'form': form,
        'usermembership':usermembership})



def attend_edit(request, detail_id):
    attend = get_object_or_404(Attend, id=detail_id)
    group = attend.attendance
    usermembership = get_object_or_404(Membership, group=group, person=request.user)
    membership = Membership.objects.get(person=request.user, group=group)

    if request.method == 'POST':
        form = AttendForm(request.POST, instance=attend)
        if form.is_valid():
            attend = form.save()
            return render(request, 'attendance/attend_detail.html', {
                'group':group,
                'attend': attend,
                'membership': membership,
                'usermembership':usermembership,
            })
    else:
        form = AttendForm(instance=attend)
    return render(request, 'attendance/attend_new.html', {
        'group':group,
        'form': form,
        'usermembership':usermembership,
    })


def attend_delete(request, detail_id):
        attend = get_object_or_404(Attend, id=detail_id)
        group = attend.attendance
        membership = Membership.objects.get(person=request.user, group=group)
        usermembership = get_object_or_404(Membership, group=group, person=request.user)

        attend.delete()

start/attendance/templates/attendance/attend_detail.html
{% extends 'group_base.html' %}

{% block content %}

    <script src="https://kit.fontawesome.com/6e27c4910b.js"></script>

    <style>

        * {
            font-family: 'Nanum Gothic', sans-serif;
        }

        .attend_info {
            border: 2px solid #9b9b9b;
            border-radius: 20px;
            padding: 10px;
        }

        .attend_check {
            border: 2px solid #9b9b9b;
            border-radius: 20px;
            padding: 10px;
        }
    </style>
    <div>
        <h3 style="font-family: 'Nanum Gothic', sans-serif; font-weight: bold;">{{ attend.title }} 출석 체크</h3><br/>
        <div class="attend_info"> {# 출석 띄우기 #}
            <div>
                <h4 style="font-family: 'Nanum Gothic', sans-serif; font-weight: bold;">출석 정보</h4>
            </div>
            <div>
                <strong>모임일시 </strong>{{ attend.gather_datetime|date:"Y-m-d H:i" }}
            </div>
            <div>
                <strong>출석 가능 기한 </strong>{{ attend.expired_datetime|date:"Y-m-d H:i" }}
            </div>
        </div>
        {% if usermembership.is_mn_stf %}
            <div class="wrap mt-3">
                <a href="{% url "attendance:attend_edit" attend.id %}" style="color: #a6a6a6;
        font-size: 14px;">출석 수정</a>
                <a href="{% url "attendance:attend_delete" attend.id %}" style="color: #a6a6a6;
        font-size: 14px; margin-left: 10px;">출석 삭제</a>
                {# 권한 : 매니저랑 스탭이 접속할때만 버튼 생성됨 #}
            </div>
        {% endif %}
        <hr/>

        <div class="attend_check">
            <h4 style="font-family: 'Nanum Gothic', sans-serif; font-weight: bold;">출석하기</h4>
            <div> {# 출석용 폼 띄우기 #}
                {% if attend.attend_status == '정상 출석 가능' %}
                    <div>
                        <form action="#" method="POST">
                            {% csrf_token %}
                            <div>스터디장에게 문의한 후 출석코드를 입력하세요</div>
                            <div>현재 정상 출석 가능합니다</div>
                            <div style="font-family: 'Nanum Gothic', sans-serif; font-weight: bold;">
                                {{ form }}
                                <input class="btn btn-primary" type="submit" value="출석"></div>
                        </form>
                    </div>
                {% elif attend.attend_status == '지각 출석 가능' %}
                    <div>
                        <form action="#" method="POST">
                            {% csrf_token %}
                            <div>{{ form.as_p }}</div>
                            <div>스터디장에게 문의한 후 출석코드를 입력하세요</div>
                            <div>현재 지각 출석입니다</div>
                            <input type="submit" value="출석하기"/>
                        </form>
                    </div>
                {% else %}
                    <div>
                        <div>{{ attend.attend_status }}입니다. 출석 할 수 없습니다.</div>
                    </div>
                {% endif %}
            </div>
        </div>

        <hr/>

        <div>
            <div>
                <h4 style="font-family: 'Nanum Gothic', sans-serif; font-weight: bold;">출석한 사람 명단</h4>
            </div>
            <div class="d-flex justify-content-start flex-wrap">
                <div class="wrap1 m-3">
                    {% if instances_attend %}
                        <div><strong>출석한자</strong></div>
                        {% for instance in instances_attend %}
                            <div>
                                {{ instance.attend_user }} | {{ instance.arrive_time|date:"Y-m-d H:i" }} | <p
                                    style="color: green">
                                정상출석</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="wrap2 m-3">
                    {% if instances_late %}
                        <div><strong>지각한자</strong></div>
                        {% for instance in instances_late %}
                            <div>
                                {{ instance.attend_user }} | {{ instance.arrive_time }} | <p
                                    style="color: orange">{{ instance.sub_time }}분 지각</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

                <div class="wrap3 m-3">
                    <div><strong>출석하지 않은 자들</strong></div>
                    <div>
                        <small>사정이 있다면 스터디장에게 말하기!</small>
                        <br/>
                        <small>출석 만료 시간이 지나면 결석으로 처리됩니다</small>
                    </div>
                    {% for instance in instances_none %}
                        <div>
                            {{ instance.attend_user }} | <p style="color: red">{{ instance.attend_check }}</p>
                        </div>
                    {% endfor %}
                    {% if instances_absence %}
                        {% for instance in instances_absence %}
                            <div>
                                {{ instance.attend_user }} | <p style="color: red">{{ instance.attend_check }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>

            </div>

            <hr style="border: 3px solid #d7d7d7; border-radius: 100%;">

            <table class="table table-hover">
                <thead>
                <tr>
                    <td>출석</td>
                    <td>출석 기한</td>
                    <td>출석 가능 여부</td>
                </tr>
                </thead>

                <tbody>
                {% for post in posts %}
                    <tr>
                        <td><a href="{% url 'attendance:attend_detail' group.id post.id %}">{{ post.title }}</a></td>
                        <td>{{ post.init_datetime|date:"Y-m-d H:i" }}부터 {{ post.expired_datetime|date:"H:i" }}까지 출석 가능
                        </td>
                        <td>{{ post.attend_status }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <hr>

            <div class="d-flex justify-content-between">
                <div>
                    {% if usermembership.is_manager %}
                        <a href="{% url 'attendance:attend_new' group.id %}"><i class="fas fa-pen"> 출석 만들기</i></a>
                    {% endif %}
                </div>
                <div>
                    <a href="{% url 'study:group_detail' group.id %}"><i class="fas fa-home"> 스터디 홈</i></a>
                </div>
            </div>
{% endblock %}

start/attendance/templates/attendance/attend_list.html
{% extends 'group_base.html' %}


{% block content %}

<script src="https://kit.fontawesome.com/6e27c4910b.js"></script>

<style>
    @font-face {
        font-family: 'yg-jalnan';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }

</style>

<div>
    <h3 style="font-family: 'yg-jalnan', cursive;">출석 체크</h3>
</div>

<br>

<table class="table table-hover">
    <thead>
        <tr>
            <td>출석</td>
            <td>출석 기한</td>
            <td>출석 가능 여부</td>
        </tr>
    </thead>
    
    <tbody>
    {% for post in posts %}
    <tr>
        <td><a href="{% url 'attendance:attend_detail' group.id post.id %}">{{ post.title }}</a></td>
        <td>{{ post.init_datetime|date:"Y-m-d H:i" }}부터 {{ post.expired_datetime|date:"H:i" }}까지 출석 가능</td>
        <td>{{ post.attend_status }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<hr>

<div class="d-flex justify-content-between">
    <div>
        {% if usermembership.is_manager %}
        <a href="{% url 'attendance:attend_new' group.id %}"><i class="fas fa-pen"> 출석 만들기</i></a>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'study:group_detail' group.id %}"><i class="fas fa-home"> 스터디 홈</i></a>
    </div>
</div>
{% endblock %}

start/attendance/templates/attendance/attend_new.html
{% extends 'group_base.html' %}

{% block content %}

<style>

    * {
        font-family: 'Nanum Gothic', sans-serif;
    }

    .top {
        border: 2px solid #9b9b9b;
        border-radius: 20px;
        padding: 10px;
    }

    .bottom {
        border: 2px solid #9b9b9b;
        border-radius: 20px;
        padding: 10px;
    }

    .btn-default {
        background-color: #1976D2;
        color: #ffffff;
    }
</style>

    <div>
        <h3 style="font-family: 'Nanum Gothic', sans-serif; font-weight: bold;">출석 만들기</h3>
        <form action="#" method="POST">
            {% csrf_token %}

            <div class="top">
                <br/>
                <div>
                    <strong>{{ form.title.label_tag }}</strong>
                    {{ form.title }}
                </div>
                <div>
                    <small>{{ form.username.errors }}</small>
                    <small>출석 포스팅의 이름을 지어주세요 ex)첫 모임/주말 회식</small>
                </div>
                <br/>

                <div>
                    <div>
                        <strong>{{ form.attendance_number.label_tag }}</strong>
                        {{ form.attendance_number }}
                        <small>{{ form.attendance_number.errors }}</small>
                    </div>
                    <div>
                        <small>3~5 자리의 무작위 출석 비밀번호를 작성해주세요</small>
                    </div>
                    <div>
                        <small>이 번호를 알고 있는 팀원만 출석이 가능합니다. 공정한 출석체크에 활용하세요!</small>
                    </div>
                </div>
            </div>


            <hr/>

            <div class="bottom">
                <div>
                    <h5>모임 날짜와 시간을 지정해주세요</h5>
                </div>
                <br/>

                <div>
                    <strong>{{ form.gather_date.label_tag }}</strong>
                    {{ form.gather_date }}<br/>
                    <small>화살표를 누르면 달력이 나와요</small>
                </div>
                <br/>

                <div>
                    <strong>이번 모임은</strong>
                    <div>
                        {{ form.gather_time_ampm }} {{ form.gather_time_hour }}시 {{ form.gather_time_minute }}분까지 모여야 해요
                    </div>
                </div>
                <br/>
                <div>
                    <div>
                        모임시간 {{ form.expired_timedelta }}분 <strong>이후까지</strong> 출석이 가능합니다
                    </div>
                    <small>모임 시간이 된 이후 설정 시간이 지나면 출석이 불가능하고 결석으로 처리됩니다.<br/>60분까지 설정 가능합니다.</small>
                </div>
            </div><br/>

            <div>
                <input type="submit" value="출석 올리기" class="btn btn-primary">
            </div><br/>
        </form>
    </div>
{% endblock %}