start/assignment/urls.py
from django.urls import path
from . import views

app_name = 'assignment'

urlpatterns = [
    path('<int:group_id>/', views.assignment_home, name='assignment_home'),
    path('<int:group_id>/list/', views.assignment_list, name='assignment_list'),
    path('<int:group_id>/new/', views.assignment_new, name='assignment_new'),
    path('<int:assignment_id>/detail/', views.assignment_detail, name='assignment_detail'),
    path('<int:assignment_id>/delete/', views.assignment_delete, name='assignment_delete'),
    path('<int:assignment_id>/edit', views.assignment_edit, name='assignment_edit'),

    path('<int:assignment_id>/done_new/', views.done_new, name='done_new'),
    path('<int:group_id>/done_list/', views.done_list, name='done_list'),
    path('<int:done_id>/done_detail/', views.done_detail, name='done_detail'),
    # path('<int:group_id>/injung_rank/', views.injung_rank, name='injung_rank'),
    path('<int:done_id>/injung_plus', views.injung_plus, name='injung_plus'),

]

start/start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('table/', include('table.urls', namespace='table')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



from django.conf.urls import url
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
    url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

start/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('study/', include('study.urls', namespace='study')),
    path('studypost/', include('studypost.urls', namespace='studypost')),
    path('assignment/', include('assignment.urls', namespace='assignment')),
    path('attendance/', include('attendance.urls', namespace='attendance'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

start/assignment/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from django.conf import settings
from study.models import Group


class Assignment(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    index_in_group = models.IntegerField()
    title = models.CharField(max_length=30, verbose_name='과제명')
    content = models.TextField(verbose_name='내용')
    due_date = models.DateTimeField(verbose_name='기한')
    created_at = models.DateTimeField(auto_now_add=True)
    done_checked = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('assignment:assignment_detail', args=[self.id])

    def submitters(self):
        return [x.author for x in Done.objects.filter(assignment=self)]


class Done(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, related_name='dones')
    index_in_assignment = models.IntegerField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    done_img = models.ImageField(upload_to='AssignmentsDone')
    injung = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('assignment:done_detail', args=[self.id])

    def injung_check(self):
        return [x.author for x in Injung_history.objects.filter(done=self)]

    def index_in_group(self):
        dones = [x for x in Done.objects.filter(assignment__group=self.assignment.group).order_by('created_at')]
        return dones.index(self)+1


class Injung_history(models.Model):
    done = models.ForeignKey(Done, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

start/assignment/forms.py
from django import forms
from django.forms import DateInput

from .models import Assignment, Done


class AssignmentForm(forms.ModelForm):

    AMPM_CHOICES = (
        ('', '오전오후'),
        ('AM', '오전'),
        ('PM', '오후')
    )

    TIME_CHOICES = (
        ('', '시각을 고르세요'),
        (1, '1'), (2, '2'), (3, '3'), (4, '4'),
        (5, '5'), (6, '6'), (7, '7'), (8, '8'),
        (9, '9'), (10, '10'), (11, '11'), (12, '12'),
    )

    MINUTE_CHOICES = (
        ('', '분을 고르세요'),
        (0, '00'), (5, '05'), (10, '10'), (15, '15'),
        (20, '20'), (25, '25'), (30, '30'), (35, '35'),
        (40, '40'), (45, '45'), (50, '50'), (55, '55'),
    )

    due_date = forms.DateField(
        widget=DateInput(attrs={'type': 'date'}),
        label='날짜'
    )
    due_date_ampm = forms.ChoiceField(label='이번 과제는', choices=AMPM_CHOICES)
    due_date_hour = forms.ChoiceField(label='시', choices=TIME_CHOICES)
    due_date_minute = forms.ChoiceField(label='분', choices=MINUTE_CHOICES)

    class Meta:
        model = Assignment
        fields = ['title', 'content']
        labels = {
            'title': '과제명',
            'content': '내용',
        }


class DoneForm(forms.ModelForm):
    class Meta:
        model = Done
        fields = ('done_img',)
        labels = {
            'done_img': '이미지 첨부',
        }

start/assignment/views.py
import random
from datetime import datetime, time
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

from attendance.views import gather_time_hour_function
from study.models import Group, Membership
from .models import Assignment, Done, Injung_history
from .forms import AssignmentForm, DoneForm
from study.views import manager_required, mn_stf_required



def assignment_home(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    usermembership = Membership.objects.get(group=group, person=request.user)
    assignments = Assignment.objects.filter(group=group).order_by('-created_at')[:5]
    dones = Done.objects.filter(assignment__group=group).order_by('-created_at')[:3]
    now = datetime.now()

    ctx = {
        'group': group, 'usermembership': usermembership, 'assignments': assignments, 'dones': dones, 'now': now,
        'n_assignment': len(assignments), 'n_dones': len(dones),
    }
    return render(request, 'assignment/assignment_home.html', ctx)


def assignment_list(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    usermembership = Membership.objects.get(group=group, person=request.user)
    assignments = Assignment.objects.filter(group=group).order_by('-created_at')
    num = len(assignments)
    now = datetime.now()
    return render(request, 'assignment/assignment_list.html', {
        'group': group, 'assignments': assignments, 'num': num, 'now': now,
        'usermembership':usermembership,
    })



def assignment_new(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    usermembership = Membership.objects.get(group=group, person=request.user)
    if Membership.objects.get(group=group, person=request.user).role == 'MEMBER':
        messages.warning(request, '매니저와 스탭만 과제를 등록할 수 있습니다.')
        return redirect('assignment:assignment_list', group_id)

    if request.method == 'POST':
        form = AssignmentForm(request.POST)

        if form.is_valid():
            assignment = form.save(commit=False)
            assignment.group = group
            assignment.index_in_group = len(Assignment.objects.filter(group=group)) + 1

            date = form.cleaned_data['due_date']

            due_time = time(
                gather_time_hour_function(
                    form.cleaned_data['due_date_hour'],
                    form.cleaned_data['due_date_ampm']
                ),
                int(form.cleaned_data['due_date_minute'])
            )

            due_date = datetime.combine(date, due_time)

            assignment.due_date = due_date
            assignment.save()
            return redirect(assignment)

    else:
        form = AssignmentForm()
        return render(request, 'assignment/assignment_new.html',
                      {'form': form, 'group':group,
                       'usermembership':usermembership})


def assignment_detail(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id)
    group = assignment.group
    assignments = Assignment.objects.filter(group=group).order_by('-created_at')
    user = request.user
    usermembership = Membership.objects.get(group=group, person=request.user)
    membership = Membership.objects.get(person=user, group=group)
    dones = Done.objects.filter(assignment=assignment)
    authors = [x.author for x in dones]
    now = datetime.now()

    ctx = {'assignment': assignment, 'assignments': assignments,
        'group': group, 'dones': dones, 'authors': authors,
          'num': len(dones), 'usermembership': usermembership, 'membership': membership,
          'now': now, 'user': user, }
    return render(request, 'assignment/assignment_detail.html', ctx)


def done_new(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id)
    group = assignment.group
    usermembership = Membership.objects.get(group=group, person=request.user)
    if datetime.now() >= assignment.due_date:
        messages.warning(request, '제출기한이 지났습니다.')
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    elif request.method == 'POST':
        form = DoneForm(request.POST, request.FILES)
        if form.is_valid():
            done = form.save(commit=False)
            done.author = request.user
            done.assignment = assignment
            done.index_in_assignment = len(Done.objects.filter(assignment=assignment))+1
            done.save()
            return redirect(done)
    else:
        form = DoneForm()
        return render(request, 'assignment/done_new.html', {
            'form': form, 'assignment': assignment,
        'group':group,
        'usermembership':usermembership,})


def done_list(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    dones = Done.objects.filter(assignment__group=group).order_by('-created_at')
    num = len(dones)
    ctx = {'group': group, 'dones': dones, 'num': num,}
    return render(request, 'assignment/done_list.html', ctx)


def done_detail(request, done_id):
    done = get_object_or_404(Done, id=done_id)
    group = done.assignment.group
    dones = Done.objects.filter(assignment__group=group).order_by('-created_at')
    usermembership = Membership.objects.get(group=group, person=request.user)
    ctx = {
        'dones': dones,
        'group': group,
        'done': done,
        'usermembership': usermembership,
    }

    return render(request, 'assignment/done_detail.html', ctx )


def injung_plus(request, done_id):
    done = get_object_or_404(Done, id=done_id)
    original_author = Membership.objects.get(person=done.author, group=done.assignment.group)
    injungs = Injung_history.objects.filter(done=done)
    authors = [x.author for x in injungs]

    if done.author == request.user:
        messages.warning(request, "너무 잘하시긴 했어요.. 그렇지만 자신의 과제에는 인정을 누를 수 없습니다.")
        return redirect(done)
    elif request.user in authors:
        when = injungs.get(author=request.user).created_at
        messages.warning(request, "{:%Y-%m-%d}에 이미 인정하셨습니다!".format(when))
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        done.injung += 1
        original_author.admit_assign += 1
        original_author.total_admit += 1
        done.save()
        original_author.save()
        new_injung = Injung_history.objects.create(author=request.user, done=done,)

        memberships = Membership.objects.filter(group=done.assignment.group)
        for m in memberships:
            m.rank = 1
            for mc in memberships:
                if m.total_admit < mc.total_admit:
                    m.rank += 1
            m.save()

        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



def assignment_edit(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id)
    group = assignment.group
    usermembership = Membership.objects.get(group=group, person=request.user)


    if request.method == 'POST':
        form = AssignmentForm(request.POST, instance=assignment)
        if form.is_valid():
            assignment = form.save(commit=False)
            date = form.cleaned_data['due_date']

            due_time = time(
                gather_time_hour_function(
                    form.cleaned_data['due_date_hour'],
                    form.cleaned_data['due_date_ampm']
                ),
                int(form.cleaned_data['due_date_minute'])
            )

            due_date = datetime.combine(date, due_time)

            assignment.due_date = due_date
            assignment.save()
            return redirect(assignment)
    else:
        form = AssignmentForm(instance=assignment)
    return render(request, 'assignment/assignment_new.html', {
        'group':group,
        'form': form,
        'usermembership':usermembership,
    })



def assignment_delete(request, assignment_id):
    assignment = get_object_or_404(Assignment, id=assignment_id)
    group = assignment.group
    usermembership = Membership.objects.get(group=group, person=request.user)
    assignment.delete()

    assignment = Assignment.objects.filter(group=group).order_by('created_at').last()
    done = Done.objects.filter(assignment=assignment).order_by('created_at').last()

    return render(request, 'assignment/assignment_home.html', {
        'assignment': assignment,
        'done': done,
        'group': group,
        'usermembership':usermembership,
    })


'''
def admit_rank(request, group_id):
    group = get_object_or_404(Group, id=group_id)
    memberships = Membership.objects.filter(group=group)
    users = [x.person for x in memberships]
    injung_rank = []

    for user in users:
        dones = Done.objects.filter(author=user)
        total_injung = sum([int(x.injung) for x in dones])
        injung_rank.append(total_injung)

    injung_rank.sort(reverse=True)

    while True:
        random.shuffle(users)
        injung_rank2 = []
        for user in users:
            dones = Done.objects.filter(author=user)
            total_injung = sum([int(x.injung) for x in dones])
            injung_rank2.append(total_injung)

        if injung_rank == injung_rank2:
            break
        else:
            continue


    return render(request, 'assignment/injung_rank.html', {
        'user_list': users,
    })
'''

start/assignment/templates/assignment/assignment_detail.html
{% extends 'group_base.html' %}

{% block content %}

<script src="https://kit.fontawesome.com/6e27c4910b.js"></script>

{{ message.message }}

    <div class="jumbotron">
    {% if membership.role != 'MEMBER' %}
        <a href="{% url "assignment:assignment_delete" assignment.id %}" class="btn btn-primary" style="float:right; margin-left: 2px">삭제</a>
        <a href="{% url "assignment:assignment_edit" assignment.id %}" class="btn btn-primary" style="float:right">수정</a>
    {% endif %}
    <h1 class="display-4">{{ assignment.title }}</h1>
        <p class="lead">{{ assignment.content|linebreaks }}</p>
        <p class="lead">{{ assignment.due_date|date:"Y-m-d H:i" }} 까지 {% if assignment.due_date <= now %}(기한 지남){% endif %}</p>
    <hr class="my-4">

        {% if user in authors %}
        <p>이미 인증하셨습니다! 멋져요~>_<</p>
        {% else %}
        <a href="{% url "assignment:done_new" assignment.id %}"
           class="btn btn-{% if assignment.due_date <= now %}secondary disabled{% else %}primary{% endif %}">인증하기</a>
        {% endif %}
    </div>


<h2>인증한 사람들 </h2>

{% if num == 0 %}
    <hr/>
    아무도 인증하지 않았어요 ㅠ_ㅠ
{% else %}
        <table class="table" >
            <thead>
                <tr align="center" style="border-top:2px solid #1976D2; border-bottom:2px solid #1976D2;">
                    <th scope="col">등수</th>
                    <th scope="col">이름</th>
                    <th scope="col">인증 시간</th>
                    <th scope="col">인정?</th>
                </tr>
            </thead>
            <tbody>
                {% for done in dones %}
                <tr align="center">
                    <th scope="row">{{ done.index_in_assignment }}등</th>
                    <td>{{ done.author.nickname }}</td>
                    <td>{{ done.created_at|date:"Y-m-d H:i" }}</td>
                    <td>{% if user != done.author %}
                            {% if user in done.injung_check %}
                                이미 ㅇㅈ함
                            {% else %}
                                <a href="{% url "assignment:done_detail" done.id %}" class="btn btn-primary">인정하러 가기</a>
                            {% endif %}
                        {% else %}
                            자추 ㄴㄴ
                        {% endif %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
{% endif %}

<br>
    <div class="d-flex justify-content-end">
        <a href="{% url "assignment:assignment_list" assignment.group.id %}"><i class="fas fa-list-ul"> 목록</i></a>
    </div>

    <!-- 과제 리스트 -->
    <div class="assignment_list" style="margin-top: 30px">
        <table class="table">
                <thead>
                    <tr align="center" style="border-top:3px solid #1976D2; border-bottom:3px solid #1976D2">
                        <th scope="col">번호</th>
                        <th scope="col">제목</th>
                        <th scope="col">기한</th>
                        <th scope="col">인증 여부</th>
                    </tr>
                </thead>
                <tbody>
                        {% for assign_ment in assignments %}
                    <tr {% if assign_ment == assignment %} style="background-color: rgba(25,118,210,0.1);"{% endif %} align="center">
                        <th scope="row">
                            {% if assign_ment == assignment %}
                                현재글
                            {% else %}
                                {{ assign_ment.index_in_group }}
                            {% endif %}</th>
                        <td><a href="{% url "assignment:assignment_detail" assign_ment.id %}">{{ assign_ment.title }}</a></td>
                        <td>{{ assign_ment.due_date|date:"Y-m-d H:i" }}{% if assign_ment.due_date <= now %}(만료){% endif %}</td>
                        <td>{% if user in assign_ment.submitters %}인증 완료{% else %}미인증{% endif %}</td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
    </div>


{% endblock %}

start/assignment/templates/assignment/assignment_home.html
{% extends 'group_base.html' %}

{% block content %}

<script src="https://kit.fontawesome.com/6e27c4910b.js"></script>

<style>
    @font-face {
        font-family: 'yg-jalnan';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }
</style>

<h3 style="font-family: 'yg-jalnan';">{{ group.group_name }}의 과제 현황 >_<</h3>
<br>

<div class="d-flex justify-content-between">
<div>
<h3 style="font-family: 'yg-jalnan';">과제</h3>
</div>

<div>
    {% if usermembership.is_mn_stf %}
    <a href="{% url 'assignment:assignment_new' group.id%}"><i class="fas fa-book-open"> 과제 등록</i></a>
    {% endif %}
    <a href="{% url 'assignment:assignment_list' group.id%}" style="margin-left: 10px;"><i class="fas fa-list-ul"> 과제 목록</i></a>
</div>
</div>


{% if n_assignment == 0 %}
    등록된 과제가 없습니다 ㅠ_ㅠ
{% else %}
            <table class="table">
                <thead>
                    <tr align="center">
                        <th scope="col">과제명</th>
                        <th scope="col">기한</th>
                        <th scope="col">인증</th>
                    </tr>
                </thead>
                <tbody>
                    {% for assignment in assignments %}
                    <tr align="center">
                        <td><a href="{% url "assignment:assignment_detail" assignment.id %}">{{ assignment.title }}</a> </td>
                        <td>{{ assignment.due_date|date:"Y-m-d H:i" }}까지
                            {% if assignment.due_date <= now %}
                             (기한 지남)
                            {% endif %}</td>
                        <td>{% if user in assignment.submitters %}인증 완료
                            {% else %}
                            <a href="{% url "assignment:done_new" assignment.id %}"
                               {% if assignment.due_date <= now %}style="color: gray"{% endif %}><i class="far fa-check-circle">인증하기</i></a>
                            {% endif %}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    {% endif %}

<div class="d-flex justify-content-between mt-5">
    <div>
        <h3 style="font-family: 'yg-jalnan';">인증</h3>
    </div>
    <div>
        <a href="{% url 'assignment:done_list' group.id%}"><i class="fas fa-list-ul"> 목록</i></a>
    </div>
</div>

    {% if n_dones == 0 %}
        등록된 인증이 없습니다 ㅠ_ㅠ
    {% else %}
            <table class="table">
                <thead>
                    <tr align="center">
                        <th scope="col">제목</th>
                        <th scope="col">이미지</th>
                        <th scope="col">인정?</th>
                    </tr>
                </thead>
                <tbody>
                        {% for done in dones %}
                            <tr align="center">
                    <th scope="row">{{ done.assignment.title }}<a href="{% url "assignment:done_detail" done.id %}">
                        <br>{{ done.author.nickname }}님의 인증</a></th>
                    <td><img src="{{ done.done_img.url }}" height="200"/></td>
                    <td>{% if user != done.author %}
                            {% if user in done.injung_check %}
                                이미 ㅇㅈ함
                            {% else %}
                                <a href="{% url "assignment:injung_plus" done.id %}" class="btn btn-primary">인정</a>
                            {% endif %}
                        {% else %}
                            자추 ㄴㄴ
                        {% endif %}</td>
                            </tr>
                        {% endfor %}
                </tbody>
            </table>
    {% endif %}
{% endblock %}

start/assignment/templates/assignment/assignment_list.html
{% extends 'group_base.html' %}

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message.message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% block content %}

<script src="https://kit.fontawesome.com/6e27c4910b.js"></script>

<style>
    @font-face {
        font-family: 'yg-jalnan';
        src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_four@1.2/JalnanOTF00.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }
</style>


<h3 style="font-family: 'yg-jalnan';">{{ group.group_name }}의 과제 리스트</h3>
<br>

    <div class="d-flex justify-content-end">
        <div>
            <a href="{% url "assignment:assignment_home" group.id %}" style="margin-right: 10px;"><i
                class="fas fa-home"> 과제 홈</i></a>
        </div>
        <div>
            {% if usermembership.is_mn_stf %}
            <a href="{% url 'assignment:assignment_new' group.id%}"><i class="fas fa-book-open"> 과제 등록</i></a>
            {% endif %}
        </div>
    </div>


    {% if num == 0 %}
        <hr/>
        <p>등록된 과제가 없습니다.</p>
    {% else %}
            <table class="table">
                <thead>
                    <tr align="center">
                        <th scope="col">번호</th>
                        <th scope="col">제목</th>
                        <th scope="col">기한</th>
                        <th scope="col">인증</th>
                    </tr>
                </thead>
                <tbody>
                        {% for assignment in assignments %}
                    <tr align="center">
                        <th scope="row">{{ assignment.index_in_group }}</th>
                        <td><a href="{% url "assignment:assignment_detail" assignment.id %}">{{ assignment.title }}</a></td>
                        <td>{{ assignment.due_date|date:"Y-m-d H:i" }}{% if assignment.due_date <= now %}(만료){% endif %}</td>
                        <td>{% if user in assignment.submitters %}인증 완료
                            {% else %}
                            <a href="{% url "assignment:done_new" assignment.id %}"
                               {% if assignment.due_date <= now %}style="color: gray"{% endif %}><i class="far fa-check-circle">인증하기</i></a>
                            {% endif %}</td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
    {% endif %}
{% endblock %}

start/assignment/templates/assignment/done_detail.html
{% extends 'group_base.html' %}

{% block content %}

    {{ message.message }}


    <div class="card mb-3 text-center">
  <div class="row no-gutters align-items-center">
    <div class="col-5">
      <img src="{{ done.done_img.url }}" class="card-img" style="width:100%; height:auto">
    </div>
    <div class="col-7">
      <div class="card-body">
        <h2 class="card-title">{{ done.author }}님의 인증</h2>
        <p class="card-text">{{ done.assignment.title }} 과제에 대한 인증입니다 :)</p>
        <p class="card-text"><small class="text-muted">{{ done.created_at|date:"Y-m-d H:i" }}에 인증함</small></p>
      </div>
      <div class="card-footer align-self-end">
          {% if user != done.author %}
                    {% if user in done.injung_check %}
                        <a href="#" class="btn btn-primary disabled">인정</a>
                        <small class="text-muted">이미 인정하셨습니다.</small>
                     {% else %}
                        <a href="{% url "assignment:injung_plus" done.id %}" class="btn btn-primary btn-lg">인정</a>
                    {% endif %}
          {% else %}
              <a href="#" class="btn btn-primary disabled">인정</a>
              <small class="text-muted">자추할 수 없습니다.</small>
          {% endif %}
      </div>
    </div>
  </div>
</div>


        <div class="done_list" style="margin-top: 150px">
        <a href="{% url "assignment:assignment_home" group.id %}" class="btn btn-primary" style="float: right; margin-bottom: 5px;">과제 홈으로</a>
        <table class="table">
                <thead>
                    <tr align="center" style="border-top:3px solid #1976D2; border-bottom:3px solid #1976D2">
                        <th scope="col">번호</th>
                        <th scope="col">과제명</th>
                        <th scope="col">인증자</th>
                        <th scope="col">인정?</th>
                    </tr>
                </thead>
                <tbody>
                        {% for group_done in dones %}
                    <tr {% if group_done == done %} style="background-color: rgba(25,118,210,0.1);"{% endif %} align="center">
                        <th scope="row">
                            {% if group_done == done %}
                                현재글
                            {% else %}
                                {{ group_done.index_in_group }}
                            {% endif %}</th>
                        <td><a href="{% url "assignment:assignment_detail" group_done.assignment.id %}">{{ group_done.assignment.title }}</a></td>
                        <td>{{ group_done.author }}</td>
                        <td>{% if user != group_done.author %}
                            {% if user in group_done.injung_check %}
                                이미 ㅇㅈ함
                            {% else %}
                                <a href="{% url "assignment:done_detail" group_done.id %}" class="btn btn-primary">인정하러 가기</a>
                            {% endif %}
                        {% else %}
                            자추 ㄴㄴ
                        {% endif %}</td>
                    </tr>
                        {% endfor %}
                </tbody>
            </table>
    </div>

{% endblock %}

start/assignment/templates/assignment/done_list.html
{% extends 'group_base.html' %}

{% block content %}

<h1>인증의 전당<a href="{% url "assignment:assignment_home" group.id %}" class="btn btn-primary" style="float: right">과제 홈으로</a></h1>

    {% if num == 0 %}
        <p style="margin-top: 50px">등록된 인증이 없습니다 ㅠ_ㅠ</p>
    {% else %}
        <div class="card-group">
    {% for done in dones %}
        <div class="col-4 mt-2">
            <div class="card text-center">
                <img src="{{ done.done_img.url }}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title" style="font-weight: bold"><a href="{% url "assignment:done_detail" done.id %}">{{ done.author }}{% if user == done.author%}(나){% endif %}님의 인증</a></h5>
                <p class="card-text">{{ done.assignment.title }} 과제에 대한 <br/> 인증입니다 :) </p>
                <p class="card-text">인증 시간: {{ done.created_at|date:"Y-m-d H:i" }}</p>

            </div>
            {% if user != done.author %}
            <div class="card-footer">
                    {% if user in done.injung_check %}
                        이미 ㅇㅈ하셨습니다
                     {% else %}
                        <div style="text-align: center"><a href="{% url "assignment:injung_plus" done.id %}" class="btn btn-primary">인정</a></div>
                    {% endif %}
                </div>{% endif %}
        </div>
        </div>
    {% endfor %}
    </div>

    {% endif %}



{% endblock %}

start/assignment/templates/assignment/done_new.html
{% extends "group_base.html" %}

{% block content %}
<form action="" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    <h1>{{ assignment.title }} 과제 인증</h1>
    <hr/>
    <table>
        {{ form.as_table }}
    </table>

    <div class="buttons" style="margin-top: 10px">
        <button type="submit" class="btn btn-primary">제출</button>
        <button type="submit" class="btn btn-primary" onclick="history.back(-1);">취소</button>
    </div>
</form>

{% endblock %}

start/assignment/templates/assignment/injung_rank.html
{% extends 'group_base.html' %}


{% block content %}

<ol>
{% for user in users %}

<li>{{ user }}</li>

{% endfor %}
</ol>

{% endblock %}